name = "Runs By Us"
prefix = "rbu"
author = "joko // Jonas"
sigversion = 3
version = "1.0.2" # NB: this is not the real version number. We use git tags.
reuse_private_key = false
files = [
    "mod.cpp",
	"LICENSE",
	"README.md"
]
include = ["./include"]
