name = "Runs By Us"
prefix = "rbu"
author = "joko // Jonas"
sig_version = 3
version = "1.1.1" # NB: this is not the real version number. We use git tags.
reuse_private_key = false
files = [
    "mod.cpp",
	"LICENSE",
	"README.md"
]
include = ["./include"]

releasebuild = [
    "@zip @RBU"
]
