name = "Runs By Us"
prefix = "rbu"
author = "joko // Jonas"
sigversion = 3
version = "2.0.0" # NB: this is not the real version number. We use git tags.
reuse_private_key = false
files = [
    "mod.cpp",
    "*.paa",
    "LICENSE"
]
include = ["./include"]
